baseURL = 'https://jianjustin.fun/'
languageCode = 'zh-CN'
title = '极北之地'
theme = 'paper'

[services.googleAnalytics]
id = ""

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'jianjustin'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'jianjustin'
  # bio = 'YOUR_BIO'


  # misc
  # disableHLJS = true                        # disable highlight.js
  # monoDarkIcon = true                       # show monochrome dark mode icon
  # gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)